public enum HAND
{
    ROYAL_FLUSH, STRAIGHT_FLUSH, FOUR_KIND, FUll_HOUSE,
    FLUSH, STRAIGHT, THREE_KIND, TWO_PAIR, PAIR, HIGH_CARD
}

public enum Rounds
{
    SETTING, FIRST, SECOND, THIRD, FINALL
}